In [1]:
import os
import numpy as np
import pandas as pd
import pickle
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [1]:
def read_excel(path):
    return pd.read_excel(path)

def perhitungan_jumlah_smp(df):
    df['SMP_MTR'] = df['MOTOR'] * 0.8
    df['SMP_MBL'] = df['MOBIL']
    df['SMP_TRK'] = df['TRUK/BUS'] * 2.5
    df['SMP'] = round(df['SMP_MTR'] + df['SMP_MBL'] + df['SMP_TRK'])
    df['JUMLAH'] = df['MOTOR'] + df['MOBIL'] + df['TRUK/BUS']
    return df

def preprocessing(df):
    encoder = OneHotEncoder(sparse_output=False)
    scaled_features = StandardScaler()
    
    # Encode HARI (pastikan encoder sudah fit pada data sebelumnya atau gunakan yang sudah disimpan)
    encoded_days = encoder.fit_transform(df[['HARI']])
    
    # Konversi 'JAM' ke total menit sejak tengah malam
    df['JAM'] = df['JAM'].apply(lambda x: int(x.split(':')[0]) * 60 + int(x.split(':')[1]))

    # Gabungkan encoded 'HARI' dengan fitur 'JAM'
    X_missing = pd.DataFrame(encoded_days, columns=encoder.get_feature_names_out(['HARI']))
    X_missing['JAM'] = scaled_features.fit_transform(df[['JAM']])

    with open('models/model_rf_mtr_losarang_2023.pkl', 'rb') as file:
        model_rf_mtr = pickle.load(file)

    # Memuat model dari file
    with open('models/model_rf_mbl_losarang_2023.pkl', 'rb') as file:
        model_rf_mbl = pickle.load(file)

    # Memuat model dari file
    with open('models/model_rf_bus_losarang_2023.pkl', 'rb') as file:
        model_rf_bus = pickle.load(file)

    # Melakukan prediksi untuk kolom MOTOR
    motor_predictions = model_rf_mtr.predict(X_missing)
    mobil_predictions = model_rf_mbl.predict(X_missing)
    bus_predictions = model_rf_bus.predict(X_missing)

    return motor_predictions, mobil_predictions, bus_predictions
    

def minutes_to_time(minutes):
    hours = minutes // 60
    minutes = minutes % 60
    return f'{int(hours):02d}:{int(minutes):02d}'

def menggabungkan_data(df, missing_times):
    # Menggabungkan data hilang dengan DataFrame utama
    df = pd.concat([df, missing_times], ignore_index=True)
    
    # Mengurutkan DataFrame berdasarkan kolom 'Waktu'
    df = df.sort_values(by=['TAHUN','BULAN','TANGGAL','HARI','JAM']).reset_index(drop=True)

    return df

In [2]:
path_1 = '../Data/Preprocessing/Data Losarang/2023/1_input_losarang_2023.xlsx'
path_2 = '../Data/Preprocessing/Data Losarang/2023/1_missing_times_losarang_2023.xlsx'

df = read_excel(path_1)
df_missing = read_excel(path_2)

print(len(df),len(df_missing))

NameError: name 'pd' is not defined

In [3]:
df_missing.head()

NameError: name 'df_missing' is not defined

In [5]:
motor_predictions, mobil_predictions, bus_predictions = preprocessing(df_missing)

In [6]:
# Menambahkan prediksi ke dalam dataframe
df_missing['MOTOR'] = motor_predictions.round()
df_missing['MOBIL'] = mobil_predictions.round()
df_missing['TRUK/BUS'] = bus_predictions.round()

In [7]:
df_missing = perhitungan_jumlah_smp(df_missing)
df_missing['JAM'] = df_missing['JAM'].apply(minutes_to_time)

In [8]:
df_missing.head()

,WAKTU,TAHUN,BULAN,TANGGAL,HARI,JAM,MOTOR,MOBIL,TRUK/BUS,JUMLAH,SMP_MTR,SMP_MBL,SMP_TRK,SMP,PEKAN
0,2023-01-20 00:15:00,2023,1,20,Friday,00:15,53.0,68.0,112.0,233.0,42.4,68.0,280.0,390.0,3
1,2023-01-20 00:30:00,2023,1,20,Friday,00:30,46.0,69.0,92.0,207.0,36.8,69.0,230.0,336.0,3
2,2023-01-20 00:45:00,2023,1,20,Friday,00:45,45.0,67.0,101.0,213.0,36.0,67.0,252.5,356.0,3
3,2023-01-20 01:00:00,2023,1,20,Friday,01:00,44.0,64.0,98.0,206.0,35.2,64.0,245.0,344.0,3
4,2023-01-20 01:15:00,2023,1,20,Friday,01:15,42.0,59.0,86.0,187.0,33.6,59.0,215.0,308.0,3

In [9]:
df_compiled = menggabungkan_data(df, df_missing)
df_compiled.head()

,WAKTU,TAHUN,BULAN,TANGGAL,HARI,JAM,MOTOR,MOBIL,TRUK/BUS,JUMLAH,SMP_MTR,SMP_MBL,SMP_TRK,SMP,PEKAN
0,2023-01-01 00:00:00,2023,1,1,Sunday,00:00,85.0,24.0,4.0,113.0,68.0,24.0,10.0,102.0,1
1,2023-01-01 00:15:00,2023,1,1,Sunday,00:15,92.0,19.0,6.0,117.0,73.6,19.0,15.0,108.0,1
2,2023-01-01 00:30:00,2023,1,1,Sunday,00:30,78.0,16.0,6.0,100.0,62.4,16.0,15.0,93.0,1
3,2023-01-01 00:45:00,2023,1,1,Sunday,00:45,78.0,23.0,4.0,105.0,62.4,23.0,10.0,95.0,1
4,2023-01-01 01:00:00,2023,1,1,Sunday,01:00,76.0,14.0,6.0,96.0,60.8,14.0,15.0,90.0,1

In [10]:
df_missing.to_excel('../Data/Preprocessing/Data Losarang/2023/2_missing_times_losarang_2023.xlsx', index=False)
df_compiled.to_excel('../Data/Preprocessing/Data Losarang/2023/2_input_losarang_2023.xlsx', index=False)